#!/usr/bin/env bash
if [ -z "$1" ]
  then
    docker-compose exec -f ../docker-compose.yml --user www-data apache grunt exec
    docker-compose exec -f ../docker-compose.yml --user www-data apache grunt less
    docker-compose exec -f ../docker-compose.yml --user www-data apache grunt deploy
    docker-compose exec -f ../docker-compose.yml --user www-data apache grunt watch
else
    docker-compose exec -f ../docker-compose.yml --user www-data apache grunt exec:$@
    docker-compose exec -f ../docker-compose.yml --user www-data apache grunt less:$@
    docker-compose exec -f ../docker-compose.yml --user www-data apache grunt watch:$@
fi
