#!/usr/bin/env bash
docker-compose -f ../docker-compose.yml up -d && \
version=$(git describe --tags $(git rev-list --tags --max-count=1))
echo "
===================== 🚀 Done 🚀 ===================

      Web server: http://localhost
      ⚙️ PHPMyAdmin: http://localhost:8080
      ✉️ Local emails: http://localhost:8025

===================== 🚀 Done 🚀 ==================="
