#!/usr/bin/env bash

DIR="$(cd "$(dirname "$0")" && pwd)"

$DIR/composer update &&
$DIR/magento setup:upgrade &&
$DIR/magento cache:clean &&
$DIR/magento cache:flush &&
$DIR/magento setup:di:compile &&
$DIR/magento setup:static-content:deploy -f en_GB fr_FR &&
$DIR/magento cache:enable &&
$DIR/magento indexer:reindex
