#!/usr/bin/env bash
docker-compose -f docker-compose.yml up -d && \
version=$(git describe --tags $(git rev-list --tags --max-count=1))
echo "
===================== 🚀 Done 🚀 ===================

      Web server + Varnish : http://localhost
      Web server - Varnish : http://localhost:66
      ⚙️ PHPMyAdmin: http://localhost:8888
      ✉️ Local emails: http://localhost:8025

===================== 🚀 Done 🚀 ==================="
